apiVersion: v1
kind: Service
metadata:
  name: acmecorp-developer-iq-productivity-service
spec:
  selector:
    app: acmecorp-developer-iq-productivity-service
  type: LoadBalancer
  ports:
  - protocol: TCP 
    port: 88
    targetPort: 88
