name: acmecorp-developer-iq-productivity-service CI/CD pipeline

env:
  GKE_CLUSTER: cluster-acmecorp-developer-iq-1
  GKE_ZONE: us-central1-c
  IMAGE: acmecorp-developer-iq-productivity-service
  TAG: prod

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: build docker image to test
      run: docker build -t test/$IMAGE:$TAG .

    - name: run pytest
      run: docker run --rm test/$IMAGE:$TAG /bin/sh -c 'pip install -r requirements.txt && pytest'

    - name: login docker hub    
      run: docker login --username ${{secrets.DOCKER_HUB_USERNAME}} --password ${{secrets.DOCKER_HUB_PASSWORD}}

    - name: build docker image
      run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/$IMAGE:$TAG .

    - name: push docker image to docker hub
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/$IMAGE:$TAG

    - name: set up gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
        project_id: ${{secrets.PROJECT_ID}}
        export_default_credentials: true
   
    - name: verify gcloud CLI
      run: gcloud version

    - name: install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: update components
      run: gcloud components update

    - name: configure docker 
      run: gcloud --quiet auth configure-docker

    - name: get GKE credentials
      run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: build docker image
      run: docker build -t gcr.io/${{secrets.PROJECT_ID}}/$IMAGE:$TAG .

    - name: push docker image to GCR
      run: docker push gcr.io/${{secrets.PROJECT_ID}}/$IMAGE:$TAG

    - name: apply deployment artifacts
      run: kubectl apply -f deployment.yml

    - name: apply service artifacts
      run: kubectl apply -f service.yml